pull_request:
  branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    - name: Build image 🔧
      run: |
        docker build "$GITHUB_WORKSPACE/src/TerribleDev.Blog.Web" -f  "src/TerribleDev.Blog.Web/Dockerfile"